Closes #56 Added disqus comment for blog post. Contact me for the Disqus account
piyush97/PiyushMehta.com pull request #58
Opened 2020-10-01 08:40 UTC by viriyadhika

## I ensure I have done the following steps

- [ ] Star the repository :star:
- [ ] Followed the [author](https://github.com/piyush97):white_check_mark:
- [ ] Tested the code properly :white_check_mark:
- [x ] Added the required feature :white_check_mark:

2020-10-01 08:48 UTC, piyush97 commented
![image](https://user-images.githubusercontent.com/18229627/94788206-e55c5500-03f0-11eb-8230-defd99a850ba.png)
@viriyadhika

2020-10-01 08:49 UTC, piyush97 commented on src/templates/post.js
>    const cups = Math.round(minutes / 5);
You need to fix these issues too.

2020-10-01 09:51 UTC, viriyadhika commented
If I'm understanding this correctly, the security settings from DisQus is configured to https://piyushmehta.tech. That's why it's unable to load DisQus from local server

2020-10-01 09:53 UTC, piyush97 commented
Hey @viriyadhika Could you please change the Disqus configurations to point to piyushmehta.com instead of .tech? 

Or is there a way to keep both?

2020-10-01 09:59 UTC, viriyadhika commented
I just changed it to piyushmehta.com, hope it works! Sorry, this is the first time I work with DisQus, not very expert with it

2020-10-01 10:04 UTC, piyush97 commented
@viriyadhika before merging could you please share the screenshot of the comments component here

2020-10-01 10:12 UTC, viriyadhika commented
import { DiscussionEmbed } from 'disqus-react'

const disqusConfig = {
    shortname: process.env.GATSBY_DISQUS_NAME,
    config: { 
      identifier: frontmatter.title,
    },
};

**<DiscussionEmbed { ...disqusConfig } />**
^This is the DisQus component

2020-10-01 10:14 UTC, piyush97 commented
Hey @viriyadhika sorry if you misunderstood but we need the screenshot of the rendered component as we can't check if it's working as required or not in the dev environment and please complete the task list too. 

:)

2020-10-01 10:21 UTC, piyush97 commented
Build has failed: https://app.netlify.com/sites/piyushmehta/deploys/5f75a8b722faa80007b7b2b8

2020-10-01 12:24 UTC, piyush97 requested changes
Need to pass the CI test and tasks required to get approved.

2020-10-01 12:26 UTC, viriyadhika commented
Alright, I'll check it out again

2020-10-04 01:49 UTC, viriyadhika commented
Hi, I'm not really sure why the deployment keeps failing. Can you assign this issue to other people? Sorry for the trouble. Thanks!

2020-10-04 03:04 UTC, closed without merging