Added a Tags renderer at the end of the blog posts
piyush97/PiyushMehta.com pull request #66
Opened 2020-10-01 11:58 UTC by mihirgupta0900

## I ensure I have done the following steps

- [x] Star the repository :star:
- [x] Followed the [author](https://github.com/piyush97):white_check_mark:
- [x] Tested the code properly :white_check_mark:
- [x] Added the required feature :white_check_mark:

2020-10-01 12:32 UTC, piyush97 commented on src/components/Tags.js
> +`;
Need to make Tag component with Styling is required, the current change only shows text, not Tags with text (Components):
![image](https://user-images.githubusercontent.com/18229627/94809334-16984d80-0410-11eb-8aa7-24b35631693d.png)

Styling the component properly would be appreciated :)

2020-10-01 12:32 UTC, piyush97 requested changes
Need to make Tag component with Styling is required, the current change only shows text, not Tags with text (Components):
![image](https://user-images.githubusercontent.com/18229627/94809334-16984d80-0410-11eb-8aa7-24b35631693d.png)

Styling the component properly would be appreciated :)

2020-10-01 12:35 UTC, mihirgupta0900 commented on src/components/Tags.js
> +`;
Sure! Do you have any specific design requests? Or should I use what's in the image?

2020-10-01 12:45 UTC, piyush97 commented on src/components/Tags.js
> +`;
@mihirgupta0900 you can use your own creativity and create a design which looks good! 
Make sure you follow the color scheme! :) 
All the best!

2020-10-02 02:34 UTC, piyush97 approved these changes
Good work! @mihirgupta0900 🎉

2020-10-02 02:40 UTC, piyush97 commented
@all-contributors please add @mihirgupta0900 as designer,code

2020-10-02 02:42 UTC, piyush97 commented
@all-contributors please add @mihirgupta0900 for design and code

2020-10-02 02:56 UTC, merged