Blog addition
piyush97/PiyushMehta.com pull request #96
Opened 2020-10-02 19:34 UTC by aesherman

## I ensure I have done the following steps

- [x] Star the repository :star:
- [x] Followed the [author](https://github.com/piyush97):white_check_mark:
- [x] Tested the code properly :white_check_mark:
- [x] Added the required feature :white_check_mark:

2020-10-02 23:01 UTC, piyush97 requested changes
Image is a required param. Please fix the build!

2020-10-02 23:01 UTC, piyush97 commented on content/blog/testing-RN-with-Appium/index.mdx
> +description: 'Software testing made simple'
Image is a required param.

2020-10-03 12:09 UTC, closed without merging

2020-10-03 16:22 UTC, aesherman commented on content/blog/testing-RN-with-Appium/index.mdx
> +description: 'Software testing made simple'
Yo if you want a change that's fine, request a change.  Don't just put a comment in and then close the PR.

2020-10-03 16:24 UTC, aesherman commented on content/blog/testing-RN-with-Appium/index.mdx
> +description: 'Software testing made simple'
Also pretty sketchy to mark your repo as participating in Hacktoberfest, require people to star and follow you, then remove the repo from participating in hacktoberfest.